language: c

os:
  - osx

compiler:
  - gcc

before_install:
  - brew update
  - brew outdated libusb || brew upgrade libusb
  - ls -l /usr/local/Cellar/libusb/
  - export LIBUSB=/usr/local/Cellar/libusb/1.0.21

script :
  - echp With LIBUS=$LIBUSB
  - make